// Last-resort static fallback catalog — used only for an instant first paint
// before the live Supabase fetch resolves, or if that fetch fails entirely.
// Kept in sync with the live `products` table; if you add/remove/reprice a
// product in Admin → Products, update the matching entry here too so this
// fallback (and cart cross-sell suggestions) never show stale data.

export const CATEGORIES = [
  { id: 'all', slug: 'all', name: 'All', count: 7 },
  { id: 'fat-loss', slug: 'fat-loss', name: 'Fat Loss', count: 1 },
  { id: 'muscle-growth', slug: 'muscle-growth', name: 'Muscle Growth', count: 3 },
  { id: 'recovery', slug: 'recovery', name: 'Recovery', count: 2 },
];

export const PRODUCTS = [
  {
    id: 'bpc-157',
    name: 'BPC-157 – 10mg',
    slug: 'bpc-157',
    category: 'recovery',
    category_name: 'Recovery',
    price: 69,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461159/dragopharma/products/bpc-157.png',
    featured: true,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Widely studied peptide for tissue repair research.',
    description: 'BPC-157 (Body Protection Compound-157) is a pentadecapeptide composed of 15 amino acids derived from human gastric juice protein.',
  },
  {
    id: 'cjc-1295-no-dac',
    name: 'CJC-1295 (No DAC) – 10mg',
    slug: 'cjc-1295-no-dac',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 69,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461161/dragopharma/products/cjc-1295-no-dac.png',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 98%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'GHRH analog studied for growth-hormone research.',
    description: 'CJC-1295 without DAC is a synthetic analog of growth hormone-releasing hormone (GHRH) designed to stimulate GH secretion.',
  },
  {
    id: 'cjc-1295-with-dac',
    name: 'CJC-1295 with DAC – 10mg',
    slug: 'cjc-1295-with-dac',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 69,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461162/dragopharma/products/cjc-1295-with-dac.png',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Long-acting GHRH analog for research use.',
    description: 'CJC-1295 with Drug Affinity Complex (DAC) provides extended half-life for biostability in laboratory investigations.',
  },
  {
    id: 'follistatin',
    name: 'Follistatin-344 – 1mg',
    slug: 'follistatin',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 199,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461167/dragopharma/products/follistatin.png',
    featured: true,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Research peptide studied for muscle-related pathways.',
    description: 'Follistatin is an autocrine glycoprotein that is potent at inhibiting myostatin signaling in muscle cellular research.',
  },
  {
    id: 'igf-1-lr3',
    name: 'IGF-1 LR3 – 1mg',
    slug: 'igf-1-lr3',
    category: 'muscle-growth',
    category_name: 'Muscle Growth',
    price: 89,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461170/dragopharma/products/igf-1-lr3.png',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Long-acting IGF-1 analog for research use.',
    description: 'Long R3 IGF-1 is an 83 amino acid analog of IGF-1 comprising the complete human IGF-1 sequence with substitution of an Arg for Glu at position 3.',
  },
  {
    id: 'retatrutide',
    name: 'Retatrutide – 10mg',
    slug: 'retatrutide',
    category: 'fat-loss',
    category_name: 'Fat Loss',
    price: 89,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461186/dragopharma/products/retatrutide.png',
    featured: false,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 99%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Multi-agonist peptide studied in metabolic research.',
    description: 'Retatrutide is a triple hormone receptor agonist targeting GIP, GLP-1, and glucagon receptors for metabolic pathways.',
  },
  {
    id: 'tb-500',
    name: 'TB-500 (Thymosin Beta-4) – 10mg',
    slug: 'tb-500',
    category: 'recovery',
    category_name: 'Recovery',
    price: 69,
    image_url: 'https://res.cloudinary.com/qjbhc75v/image/upload/v1789461193/dragopharma/products/tb-500.png',
    featured: true,
    rating: 0,
    reviews_count: 0,
    purity: '≥ 98%',
    form: 'Lyophilized',
    stock: 100,
    in_stock: true,
    short_desc: 'Peptide studied for tissue repair and recovery research.',
    description: 'TB-500 is a synthetic fraction of the naturally occurring peptide Thymosin Beta-4, studied for actin regulation and cellular migration.',
  },
];
